apiVersion: v1  
kind: Service  
metadata:  
  name: otel-collector-collector-export-service 
  namespace: postgresql
  labels:
    app: postgres
spec:  
  type: NodePort  
  ports:  
    name: otel-collector-collector
    protocol: TCP  
    port: 5432  # PostgreSQL default port  
    targetPort: 5432  
  selector:  
    app: postgres 